name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # Points to the package-lock.json inside Documentation
          cache-dependency-path: Documentation/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./Documentation

      - name: Build with VitePress
        run: npm run docs:build
        working-directory: ./Documentation

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This must point to the 'dist' folder inside your subfolder
          path: Documentation/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4