name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: Documentation/package-lock.json

      - name: Install dependencies
        # 'npm ci' is better for CI/CD than 'npm install'
        run: npm ci
        working-directory: ./Documentation

      - name: Build with VitePress
        # We manually trigger the build via the node executable to bypass shell permission issues
        run: node ./node_modules/vitepress/bin/vitepress.js build
        working-directory: ./Documentation

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Documentation/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4